---
# tasks file for roles/nginx

- name: Put nginx.conf
  template:
    src: "templates/nginx.conf"
    dest: "/nginx.conf"
    mode: 0644

- name: Run nginx container
  docker_container:
    name: nginx
    image: nginx
    mounts:
      - source: "/nginx.conf"
        target: "/etc/nginx/nginx.conf"
        type: bind
    hostname: nginx
    ports:
        - "10000:80"
    networks:
      - name: "{{ network_name }}" 
        links: "{{ web_servers.keys() | list }}"
    state: started
    recreate: yes



